name: HYUabot API Server CI

on:
  [push, pull_request]
jobs:
    lint:
      runs-on: self-hosted
      steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.4
      - uses: actions/checkout@v3
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --config .golangci.yml
    build:
      needs: [lint]
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...