name: HYUabot API Server CI

on:
  [push, pull_request]
jobs:
    build:
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v3
        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            cache: true

        - name: Install dependencies
          run: go mod download

        - name: Lint
          uses: golangci/golangci-lint-action@v3
          with:
            skip-go-installation: true
            args: --config .golangci.yml
        - name: Build
          run: go build -v ./...