name: HYUabot API Server CI

on:
  [push, pull_request]
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - uses: actions/checkout@v3
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --config .golangci.yml
          skip-pkg-cache: true
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.3
          cache: true
      - name: Install dependencies
        run: go mod download
      - name: Test
        run: go test -v ./...
        env:
          DB_HOST: ${{ secrets.POSTGRES_HOST }}
          DB_PORT: ${{ secrets.POSTGRES_PORT }}
          DB_USER: ${{ secrets.POSTGRES_ID }}
          DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DB_NAME: ${{ secrets.POSTGRES_DB }}
  build:
    needs: [lint, test]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.3
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...