// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AdminUser               string
	BusRealtime             string
	BusRoute                string
	BusRouteStop            string
	BusStop                 string
	BusTimetable            string
	Campus                  string
	CommuteShuttleRoute     string
	CommuteShuttleStop      string
	CommuteShuttleTimetable string
	Menu                    string
	NoticeCategory          string
	Notices                 string
	ReadingRoom             string
	Restaurant              string
	ShuttleHoliday          string
	ShuttlePeriod           string
	ShuttlePeriodType       string
	ShuttleRoute            string
	ShuttleRouteStop        string
	ShuttleStop             string
	ShuttleTimetable        string
	SubwayRealtime          string
	SubwayRoute             string
	SubwayRouteStation      string
	SubwayStation           string
	SubwayTimetable         string
}{
	AdminUser:               "admin_user",
	BusRealtime:             "bus_realtime",
	BusRoute:                "bus_route",
	BusRouteStop:            "bus_route_stop",
	BusStop:                 "bus_stop",
	BusTimetable:            "bus_timetable",
	Campus:                  "campus",
	CommuteShuttleRoute:     "commute_shuttle_route",
	CommuteShuttleStop:      "commute_shuttle_stop",
	CommuteShuttleTimetable: "commute_shuttle_timetable",
	Menu:                    "menu",
	NoticeCategory:          "notice_category",
	Notices:                 "notices",
	ReadingRoom:             "reading_room",
	Restaurant:              "restaurant",
	ShuttleHoliday:          "shuttle_holiday",
	ShuttlePeriod:           "shuttle_period",
	ShuttlePeriodType:       "shuttle_period_type",
	ShuttleRoute:            "shuttle_route",
	ShuttleRouteStop:        "shuttle_route_stop",
	ShuttleStop:             "shuttle_stop",
	ShuttleTimetable:        "shuttle_timetable",
	SubwayRealtime:          "subway_realtime",
	SubwayRoute:             "subway_route",
	SubwayRouteStation:      "subway_route_station",
	SubwayStation:           "subway_station",
	SubwayTimetable:         "subway_timetable",
}
